apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: 0mid-net
    app.kubernetes.io/project: 0mid-net
    app.kubernetes.io/env: test
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: mydb
  MYSQL_USER: myuser
  MYSQL_PASSWORD: password