apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: 0mid-net
    app.kubernetes.io/project: 0mid-net
    app.kubernetes.io/env: test
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: 0mid-net
    app.kubernetes.io/project: 0mid-net
    app.kubernetes.io/env: test
  ports:
    - name: mariadb
      port: 3306