apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: 0mid-net
    app.kubernetes.io/project: 0mid-net
    app.kubernetes.io/env: test
spec:
  replicas: 1
  serviceName: mariadb
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadb
      app.kubernetes.io/part-of: 0mid-net
      app.kubernetes.io/project: 0mid-net
      app.kubernetes.io/env: test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/part-of: 0mid-net
        app.kubernetes.io/project: 0mid-net
        app.kubernetes.io/env: test
    spec:
      containers:
        - name: mariadb
          image: mariadb:11
          envFrom:
            - secretRef:
                name: mariadb-secret
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
          ports:
            - name: mariadb
              containerPort: 3306
          livenessProbe:
            exec:
              command: ["kill", "-0", "1"]
          readinessProbe:
            tcpSocket:
              port: 3306
  volumeClaimTemplates:
    - metadata:
        name: mariadb-data
        labels:
          app.kubernetes.io/name: mariadb
          app.kubernetes.io/part-of: 0mid-net
          app.kubernetes.io/project: 0mid-net
          app.kubernetes.io/env: test
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi