PROJECT_DIR: "/opt/0mid-net-website"
MIGRATE_DB: "no"
SETTINGS_PROFILE: "production"
NGINX_STATIC_FILES_DIR: "/var/www"
CONTAINER_INSIDE_USER_ID: "1010"
TEMPLATE_NGINX_CONF: "no"
GET_CERTBOT_SSL: "no"
ENV_SITE_SECRET_KEY: "mysecretstring"
ENV_SITE_DB_NAME: "mydb"
ENV_SITE_DB_USER: "myuser"
ENV_SITE_DB_PASSWORD: "password"
ENV_SITE_DB_HOST: "db"
ENV_SITE_DB_PORT: "3306"
ENV_SITE_ENV: "production"
ENV_SITE_VENV_PATH: "/home/myuser/code"
ENV_MYSQL_ROOT_PASSWORD: "root"
ENV_MYSQL_DATABASE: "mydb"
ENV_MYSQL_USER: "myuser"
ENV_MYSQL_PASSWORD: "password"