# Generated by Django 4.0.4 on 2022-05-16 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_menu_icon_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="submenu",
            options={"ordering": ["order"]},
        ),
    ]
