# Generated by Django 4.0.4 on 2022-07-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_menu_options_alter_submenu_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='SubMenu',
        ),
    ]
