# Generated by Django 4.1 on 2022-10-23 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_submenu_parent_delete_menu_delete_submenu"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, upload_to="favicon/", verbose_name="favicon"
                    ),
                ),
                (
                    "copyr",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Copyright text"
                    ),
                ),
                (
                    "google_analytics",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Google analytics ID"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        default="https://#",
                        max_length=100,
                        verbose_name="URL",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(unique=True, verbose_name="Order Number"),
                ),
                (
                    "icon_type",
                    models.CharField(
                        choices=[
                            ("DD", "Has submenu"),
                            ("N", "Don't have submenu"),
                            ("DI", "Is deactivate"),
                        ],
                        default="N",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SubMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        default="https://#",
                        max_length=100,
                        verbose_name="URL",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(unique=True, verbose_name="Order Number"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.menu"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
