version: "3"

services:
  web:
    build: .
    image: 0mid.net:latest
    container_name: 0mid-net-web
    restart: unless-stopped
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - /var/www/web_static:/opt/app/static_root
      - /var/www/web_media:/opt/app/media
    environment:
      - SITE_DB_HOST=db
    env_file: .env

  db:
    image: mariadb:11
    container_name: 0mid-net-mariadb
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file: .env

  scan:
    build: .
    image: 0mid.net:latest
    container_name: 0mid-net-scan
    restart: unless-stopped
    environment:
      - SITE_DB_HOST=db
    env_file: .env
    entrypoint: python
    command: manage.py daemon --settings=config.settings.production

volumes:
  mariadb_data:

# After docker compose up:
# docker compose exec web python manage.py migrate --settings=config.settings.production
# sudo chown -R omid:omid /var/www/web_static
# sudo chown -R omid:omid /var/www/web_media
# docker compose exec web python manage.py collectstatic --settings=config.settings.production
