version: "3"

services:
  web:
    build: .
    image: 0mid.net:latest
    container_name: web
    restart: no
    entrypoint: ["sh", "scripts/test.sh"]
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - SITE_DB_HOST=db
      - SITE_SECRET_KEY=testsecret
      - SITE_DB_NAME=testdb
      - SITE_DB_USER=testuser
      - SITE_DB_PASSWORD=testpass
      - SITE_DB_PORT=3306
      - SITE_ENV=production

  db:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=testroot
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpass

volumes:
  mariadb_data:

# test using: docker compose -f docker-compose.test.yaml up --build --exit-code-from web