# Generated by Django 5.2.7 on 2025-10-12 08:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(default='Blog Name', max_length=50, verbose_name='Title in menu bar')),
                ('blog_title', models.CharField(default='Blog Title', max_length=70, verbose_name='Title in blog main page')),
                ('blog_subtitle', models.CharField(blank=True, max_length=150, verbose_name='Sub-title in blog main page')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug/URL')),
                ('position', models.IntegerField(unique=True, verbose_name='Position')),
                ('meta_description', models.CharField(blank=True, max_length=200, verbose_name='Meta description tag')),
                ('keywords', models.CharField(blank=True, max_length=160, verbose_name='Meta keywords tag')),
                ('robots', models.CharField(blank=True, max_length=60, verbose_name='Meta robots tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug/URL')),
                ('subheading', models.CharField(blank=True, max_length=250, verbose_name='Subheading')),
                ('published', models.DateField(default=django.utils.timezone.now, verbose_name='Published on')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created on')),
                ('updated', models.DateField(auto_now=True, verbose_name='Updated on')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], max_length=1, verbose_name='Status')),
                ('language', models.CharField(choices=[('en', 'English'), ('fa', 'Persian')], max_length=2, verbose_name='Language')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description tag')),
                ('keywords', models.CharField(blank=True, max_length=100, verbose_name='Meta keywords tag')),
                ('robots', models.CharField(blank=True, max_length=60, verbose_name='Meta robots tag')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('tag', models.ManyToManyField(related_name='articles', to='blog.tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published'],
            },
        ),
    ]
