# Generated by Django 4.0.4 on 2022-05-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_article_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "copyr",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Copyright message in footer",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "linkedin",
                    models.URLField(
                        blank=True, default="#", verbose_name="Linkedin Account"
                    ),
                ),
                (
                    "github",
                    models.URLField(
                        blank=True, default="#", verbose_name="Github Account"
                    ),
                ),
            ],
        ),
    ]
