# Generated by Django 4.0.4 on 2022-06-15 01:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_article_subheading"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuration",
            name="github",
        ),
    ]
