# Generated by Django 4.0.4 on 2022-06-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_tag_options_alter_article_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="meta_description",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Meta description tag"
            ),
        ),
    ]
