# Generated by Django 4.0.4 on 2022-06-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_configuration_robots'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='keywords',
            field=models.CharField(blank=True, max_length=100, verbose_name='Meta keywords tag'),
        ),
    ]
