PROJECT_DIR: ""
MIGRATE_DB: ""
SETTINGS_PROFILE: ""
NGINX_STATIC_FILES_DIR: ""
CONTAINER_INSIDE_USER_ID: ""
TEMPLATE_NGINX_CONF: ""
GET_CERTBOT_SSL: ""
ENV_SITE_SECRET_KEY: ""
ENV_SITE_DB_NAME: ""
ENV_SITE_DB_USER: ""
ENV_SITE_DB_PASSWORD: ""
ENV_SITE_DB_HOST: ""
ENV_SITE_DB_PORT: ""
ENV_SITE_ENV: ""
ENV_SITE_VENV_PATH: ""
ENV_MYSQL_ROOT_PASSWORD: ""
ENV_MYSQL_DATABASE: ""
ENV_MYSQL_USER: ""
ENV_MYSQL_PASSWORD: ""