apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: 0mid-net
    app.kubernetes.io/project: 0mid-net
    app.kubernetes.io/env: test
data:
  SITE_DB_NAME: mydb
  SITE_DB_USER: myuser
  SITE_DB_PORT: "3306"