apiVersion: v1
kind: Secret
metadata:
  name: web-secret
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: 0mid-net
    app.kubernetes.io/project: 0mid-net
    app.kubernetes.io/env: test
stringData:
  SITE_SECRET_KEY: mysecretstring
  SITE_DB_PASSWORD: password