# Generated by Django 4.1 on 2022-10-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0002_remove_job_tried'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='Title tag')),
                ('description', models.CharField(blank=True, max_length=160, verbose_name='Meta description tag')),
                ('keywords', models.CharField(blank=True, max_length=160, verbose_name='Meta keywords tag')),
            ],
        ),
    ]
