# Generated by Django 4.1 on 2022-11-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0004_scanconfig_author_scanconfig_robots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='command',
            field=models.CharField(choices=[('pi', 'ping instantly'), ('p', 'ping'), ('hi', 'http instantly'), ('h', 'http')], max_length=2, verbose_name='Command type'),
        ),
    ]
