# Generated by Django 4.0.4 on 2022-06-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="subheading",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Subheading"
            ),
        ),
    ]
