---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Check whether Nginx is installed
  ansible.builtin.fail:
    msg: "Nginx is not installed!"
  when: "'nginx' not in ansible_facts.packages"

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Check whether Nginx service is active
  ansible.builtin.fail:
    msg: "Nginx service is not active!"
  when: ansible_facts['services']['nginx.service']['state'] != 'running'

- name: Check whether Nginx service is enabled
  ansible.builtin.fail:
    msg: "Nginx service is not active!"
  when: ansible_facts['services']['nginx.service']['status'] != 'enabled'

- name: copy firewall rules
  ansible.builtin.template:
    src: nginx-config.j2
    dest: /etc/nginx/conf.d/0mid.net.conf
    owner: root
    group: root
    mode: '0644'

- name: Verify Nginx config
  command: nginx -t
  changed_when: false

- name: Reload Nginx config
  command: nginx -s reload
