# Generated by Django 4.0.4 on 2022-05-06 07:33

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(blank=True, max_length=60, verbose_name='Website title')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='Title tag')),
                ('description', models.CharField(blank=True, max_length=160, verbose_name='Meta description tag')),
                ('robots', models.CharField(blank=True, max_length=160, verbose_name='Meta robots tag')),
                ('author', models.CharField(blank=True, max_length=160, verbose_name='Meta author tag')),
                ('keywords', models.CharField(blank=True, max_length=160, verbose_name='Meta keywords tag')),
                ('favicon', models.ImageField(blank=True, upload_to='favicon/', verbose_name='favicon')),
                ('copyr', models.CharField(blank=True, max_length=100, verbose_name='Copyright text')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=50, verbose_name='University Name')),
                ('level', models.CharField(max_length=20, verbose_name='Education Level')),
                ('title', models.CharField(max_length=50, verbose_name='Field of Study')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start', models.DateField(verbose_name='Start Date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='End Date')),
            ],
            options={
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('end'), descending=True, nulls_first=True)],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Job Title')),
                ('company', models.CharField(max_length=50, verbose_name='Company Name')),
                ('logo', models.ImageField(upload_to='company_logos/', verbose_name='Company Logo')),
                ('url', models.URLField(default='https://#', max_length=50, verbose_name='Company URL')),
                ('company_details', models.TextField(blank=True, verbose_name='Company Description')),
                ('start', models.DateField(verbose_name='Start Date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('location', models.CharField(blank=True, max_length=50, verbose_name='Location/Remote')),
                ('summary', models.TextField(blank=True, verbose_name='Job Description')),
            ],
            options={
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('end'), descending=True, nulls_first=True)],
            },
        ),
        migrations.CreateModel(
            name='Jumbotron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.CharField(max_length=50, verbose_name='Welcome Message')),
                ('title', models.CharField(max_length=50, verbose_name='Title/Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('picture', models.ImageField(upload_to='jumbotron_picture/', verbose_name='Picture/Avatar')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Language')),
                ('level', models.CharField(max_length=100, verbose_name='Proficiency')),
                ('order', models.IntegerField(unique=True, verbose_name='Order Number')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.URLField(blank=True, default='#', verbose_name='Linkedin Account')),
                ('github', models.URLField(blank=True, default='#', verbose_name='Github Account')),
                ('stackexchange', models.URLField(blank=True, default='#', max_length=254, verbose_name='Stackexchange Account')),
                ('instagram', models.URLField(blank=True, default='#', verbose_name='Instagram Account')),
                ('twitter', models.URLField(blank=True, default='#', verbose_name='Twitter Account')),
            ],
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Soft Skill')),
                ('order', models.IntegerField(unique=True, verbose_name='Order Number')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TechSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Technical Skill')),
                ('certs', models.CharField(blank=True, max_length=100, verbose_name='Certification(s)')),
                ('details', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.IntegerField(unique=True, verbose_name='Order Number')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
