# Generated by Django 4.0.4 on 2022-05-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="logo",
            field=models.ImageField(
                blank=True, upload_to="company_logos/", verbose_name="Company Logo"
            ),
        ),
    ]
