# Generated by Django 4.0.4 on 2022-04-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end',
            field=models.DateField(blank=True, verbose_name='End Date'),
        ),
    ]
