# Generated by Django 4.0.4 on 2022-05-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_job_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='og_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='Open graph title'),
        ),
    ]
