# Generated by Django 4.0.4 on 2022-04-29 12:55

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_job_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=50, verbose_name='University Name')),
                ('level', models.CharField(max_length=20, verbose_name='Education Level')),
                ('title', models.CharField(max_length=50, verbose_name='Field of Study')),
                ('description', models.TextField(verbose_name='Description')),
                ('start', models.DateField(verbose_name='Start Date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='End Date')),
            ],
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('end'), descending=True, nulls_first=True)]},
        ),
    ]
