# Generated by Django 4.0.4 on 2022-05-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0004_configuration_twitter_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jumbotron",
            name="picture",
            field=models.ImageField(
                blank=True,
                upload_to="jumbotron_picture/",
                verbose_name="Picture/Avatar",
            ),
        ),
    ]
