# Generated by Django 4.0.4 on 2022-04-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_softskill_alter_education_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Soft Skill')),
                ('details', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.IntegerField(unique=True, verbose_name='Order Number')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
