# Generated by Django 4.0.4 on 2022-05-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_configuration_google_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='google_analytics',
            field=models.CharField(blank=True, max_length=50, verbose_name='Google analytics ID'),
        ),
    ]
