# Generated by Django 4.0.4 on 2022-04-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_softskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Language')),
                ('level', models.CharField(max_length=100, verbose_name='Proficiency')),
                ('order', models.IntegerField(unique=True, verbose_name='Order Number')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
