# Generated by Django 4.0.4 on 2022-07-01 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_alter_configuration_google_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('url', models.URLField(blank=True, default='https://#', max_length=100, verbose_name='URL')),
                ('order', models.IntegerField(unique=True, verbose_name='Order Number')),
                ('icon_type', models.CharField(choices=[('DD', 'Has submenu'), ('N', "Don't have submenu"), ('DI', 'Is deactivate')], default='N', max_length=2)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('url', models.URLField(blank=True, default='https://#', max_length=100, verbose_name='URL')),
                ('order', models.IntegerField(unique=True, verbose_name='Order Number')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.menu')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
