# Generated by Django 4.0.4 on 2022-05-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_socialaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='Title tag')),
                ('description', models.CharField(blank=True, max_length=160, verbose_name='Meta description tag')),
                ('robots', models.CharField(blank=True, max_length=160, verbose_name='Meta robots tag')),
                ('author', models.CharField(blank=True, max_length=160, verbose_name='Meta author tag')),
                ('keywords', models.CharField(blank=True, max_length=160, verbose_name='Meta keywords tag')),
                ('favicon', models.ImageField(blank=True, upload_to='favicon/', verbose_name='favicon')),
                ('copyr', models.CharField(blank=True, max_length=100, verbose_name='Copyright text')),
            ],
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='github',
            field=models.URLField(blank=True, default='#', verbose_name='Github Account'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='instagram',
            field=models.URLField(blank=True, default='#', verbose_name='Instagram Account'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='linkedin',
            field=models.URLField(blank=True, default='#', verbose_name='Linkedin Account'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='stackexchange',
            field=models.URLField(blank=True, default='#', max_length=254, verbose_name='Stackexchange Account'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='twitter',
            field=models.URLField(blank=True, default='#', verbose_name='Twitter Account'),
        ),
    ]
