# Generated by Django 4.0.4 on 2022-05-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_configuration_alter_socialaccount_github_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softskill',
            name='details',
        ),
        migrations.AlterField(
            model_name='softskill',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Soft Skill'),
        ),
    ]
