# Generated by Django 4.0.4 on 2022-05-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_remove_softskill_details_alter_softskill_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(max_length=20, verbose_name='Education Level'),
        ),
    ]
