# Generated by Django 4.1 on 2023-01-05 08:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0013_resumeconfig_skills_style"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechSkillText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", ckeditor.fields.RichTextField(verbose_name="Content")),
            ],
        ),
    ]
